### ISSUE TITLE
'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by mjmeintjes** [pesterhazy/zprint-mode.el#5]
When trying to run `zprint` on a clojure file I get the following. It might be work adding the option to specify a local zprint path.
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   604    0   604    0     0    703      0 --:--:-- --:--:-- --:--:--   702

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0 47.0M    0  254k    0     0    99k      0  0:08:04  0:00:02  0:08:02  239k
  6 47.0M    6 3065k    0     0   896k      0  0:00:53  0:00:03  0:00:50 1592k
 18 47.0M   18 8825k    0     0  2007k      0  0:00:23  0:00:04  0:00:19 3043k
 29 47.0M   29 13.7M    0     0  2608k      0  0:00:18  0:00:05  0:00:13 3608k
 40 47.0M   40 19.1M    0     0  3064k      0  0:00:15  0:00:06  0:00:09 3998k
 52 47.0M   52 24.7M    0     0  3430k      0  0:00:14  0:00:07  0:00:07 5192k
 64 47.0M   64 30.5M    0     0  3719k      0  0:00:12  0:00:08  0:00:04 5658k
 77 47.0M   77 36.3M    0     0  3955k      0  0:00:12  0:00:09  0:00:03 5665k
 89 47.0M   89 42.1M    0     0  4153k      0  0:00:11  0:00:10  0:00:01 5820k
100 47.0M  100 47.0M    0     0  4283k      0  0:00:11  0:00:11 --:--:-- 5894k
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/matthys/.pyenv/versions/3.7.1/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 25: invalid continuation byte
```

**Comment by pesterhazy** [comment]
@mjmeintjes thanks for the report. This should be fixed in 0.2 - let me know if it still doesn't work
